# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "swift-http-import"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/swift-http-import"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "certs/*.crt",
  "certs/README.md",
  "examples/*.yaml",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/cactus/go-statsd-client/v6/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/google/go-github/v80/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/gophercloud/gophercloud/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/gophercloud/utils/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/klauspost/compress/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/majewsky/schwift/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-api-declarations/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-bits/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/ulikunitz/xz/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/go.uber.org/automaxprocs/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/golang.org/x/crypto/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/net/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/oauth2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/pault.ag/go/debian/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/davecgh/go-spew/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = [
  "vendor/github.com/google/go-cmp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/go-querystring/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/jpillora/longestcommon/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kr/pretty/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kr/text/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/pmezard/go-difflib/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/prashantv/gostub/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/sergi/go-diff/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/stretchr/testify/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/gopkg.in/check.v1/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/pault.ag/go/topsort/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"
